### ISSUE TITLE
uneven edge length scaling in networkBFEalloc

### ISSUE THREAD

**Issue by JenkeScheen** [forcefield/DiffNet#1]
I'm trying to generate a diffnet in spring_layout using a 11x11 symmetrical sij with np.inf on diagonal:
[sij_sym.npy.zip](https://github.com/forcefield/DiffNet/files/4890228/sij_sym.npy.zip)
```
%matplotlib inline
import matplotlib
from matplotlib import pyplot as plt
matplotlib.rcParams['font.size'] = 20
import networkx as nx
import numpy as np
from cvxopt import matrix
import diffnet as dn
import graph as gph
from netbfe import *

sij = matrix(np.sqrt(np.load("sij_sym.npy")))

#insert delta with stdev=1 for first s_ii:
delta = sij.shape[0] * [np.inf]
fict_delta = [1] + delta[1:]

#minimal graph generation:
n = networkBFEalloc( sij, N=1000, delta=fict_delta)
G = gph.diffnet_to_graph( n)
gph.draw_diffnet_graph( G, widthscale=1e-1, nodescale=5)
```
however this returns a graph where the origin node is distanced, skewing the network:
![image](https://user-images.githubusercontent.com/43140137/86911958-0a07a000-c114-11ea-93a8-482d15dbeeff.png)

**Comment by forcefield** [comment]
Do you have the same problem when the diagonal elements of sij are not np.inf?

**Comment by JenkeScheen** [comment]
looks like it, yes. This matrix:
![image](https://user-images.githubusercontent.com/43140137/87018856-bfe0f600-c1c9-11ea-9010-dd3cb9692fba.png)
produces a similarly skewed network with the same code:
![image](https://user-images.githubusercontent.com/43140137/87019007-fd458380-c1c9-11ea-83b3-ba24ed7f77a4.png)

**Comment by forcefield** [comment]
I pushed a new graph.py that might alleviate this problem.  Please see issues/001 for the results.
